"""add stripe subscription id to profiles

Revision ID: 7bd736bcb9e5
Revises: c0012709ebf9
Create Date: 2026-04-14 10:50:18.909034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bd736bcb9e5'
down_revision: Union[str, Sequence[str], None] = 'c0012709ebf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('stripe_subscription_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'stripe_subscription_id')
    # ### end Alembic commands ###
