"""add rate limit request table

Revision ID: f6b2d3e43fae
Revises: 6559a7a7f0e0
Create Date: 2026-04-06 20:06:20.562066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6b2d3e43fae'
down_revision: Union[str, Sequence[str], None] = '6559a7a7f0e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limit_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_limit_requests_identifier'), 'rate_limit_requests', ['identifier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rate_limit_requests_identifier'), table_name='rate_limit_requests')
    op.drop_table('rate_limit_requests')
    # ### end Alembic commands ###
